### ISSUE TITLE
Allow login using APInf account

### ISSUE THREAD

**Issue by tulir** [apinf/openapi-space#11]
In order to properly integrate designer with APInf, we need to make it possible to log in to space with an APInf account.

**Comment by mauriciovieira** [comment]
You can just hit /login on APInf Platform REST API.

So this project should have a configuration saying to which Platform instance it should hit the endpoints.

**Comment by tulir** [comment]
I've added `/auth/login/apinf` that takes the APInf auth token and user ID, checks them and gives a space auth token. When logging in using that method, `apinf:` is prepended to the username to avoid conflicts with normal space users.
Assuming we can send data into the designer iframe from APInf platform (client), it should be possible to simply pass the auth token and user ID to the designer and use those for seamless authentication to space.

**Comment by tulir** [comment]
It seems that [`postMessage()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) can handle communication to the `iframe`.
