### ISSUE TITLE
Install continuous integration

### ISSUE THREAD

**Issue by mauriciovieira** [apinf/openapi-space#15]
It would be interesting to have, at least, a flake8/pep8 check on a CI like Travis-CI or Circle-CI.

**Comment by MikeRalphson** [comment]
Possibly also validation of the Swagger / OpenAPI definition, using something like [swagger_spec_validator](https://github.com/Yelp/swagger_spec_validator)

**Comment by xylix** [comment]
I initialised travis to run flake8 on the feature/travis branch. Results available here https://travis-ci.org/apinf/openapi-space . I'm probably going to look at the swagger_spec_validator tomorrow.

**Comment by xylix** [comment]
Connexion already validates the OpenAPI definition when starting the server. We just need to add server start test to Travis-CI and we will get the spec testing with that.

**Comment by xylix** [comment]
Connexion testing will take quite a bit more work than I expected, so I implemented validation for the OpenAPI spec with swagger_spec_validator for now.
