### ISSUE TITLE
Consider re-licensing as EUPL

### ISSUE THREAD

**Issue by brylie** [apinf/openapi-space#21]
@ccsr has expressed interest in re-licensing this project as EUPL. This issue is to discuss the licensing question, and to develop a consensus about the project license choice.

**Comment by tulir** [comment]
Are we only considering the switch for space, or also for designer?

Previous license change issues: apinf/openapi-designer#34, apinf/openapi-designer#198

**Comment by brylie** [comment]
This discussion is regarding OpenAPI Space.

**Comment by xylix** [comment]
What are the benefits of this change from the projects viewpoint? Also what are the downsides, if there are any?

**Comment by brylie** [comment]
Ping @ccsr

**Comment by ccsr** [comment]
@xylix following
1. We need to have consistency in our modules
2. Need to have acknowledgments for contributions and they should be protected
3. Reciprocity for contributors

This change of license will not restrict anyone to use the software but it will for sure discourage using without giving acknowledgements.

**Comment by xylix** [comment]
@ccsr Okay. Should I do a pull request for the license change?

**Comment by mauriciovieira** [comment]
OK for me.

**Comment by MikeRalphson** [comment]
No problem from my point of view.

**Comment by ccsr** [comment]
@xylix lets do whatever is needed. Thanks @MikeRalphson @mauriciovieira @brylie @tulir @xylix
