### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by tulir** [apinf/openapi-space#4]
OpenAPI hub is a bit too similar to Swagger Hub, so we've decided that we should rename the project. Suggestions are welcome.

**Comment by xylix** [comment]
Apinf is thinking about reserving a domain for a hosted version of the project. We would like the name to be something which can easily be turned into a domain.

Suggestions:
* openapi.space (Project name OpenAPI space or something similar)
* openapi.download (Project name OpenAPI download or something similar)

**Comment by mauriciovieira** [comment]
+1 openapi.space - OpenApi Space is perfect

**Comment by tulir** [comment]
@brylie @bajiat Opinions/suggestions?

**Comment by brylie** [comment]
I agree with @mauriciovieira 

@MikeRalphson thoughts?

**Comment by bajiat** [comment]
OpenApi Space sounds good to me, too. Did anyone check whether the domain is available?

**Comment by tulir** [comment]
Yeah, we didn't include ideas that aren't yet available (openapi.box) or that were reserved (openapi.cloud)

**Comment by tulir** [comment]
We now have the domain https://openapi.space, so I renamed the repo to openapi-space
